name: scdp
channels:
  - defaults
dependencies:
  - python=3.12.4
  - pip:
    - torch==2.3.1
    - torchvision==0.18.1
    - torchaudio==2.3.1
    - numpy==1.26.4
    - scikit-learn==1.5.1
    - scipy==1.14.0
    - transformers==4.46.1
    - datasets==2.20.0
    - tqdm==4.66.4
    - evaluate==0.4.2
    - sentence-transformers==3.0.1